apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-simulator
  template:
    metadata:
      labels:
        app: apc-simulator
    spec:
      containers:
        - name: apc-simulator
          image: lusifar/apc-simulator:v2
          ports:
            - containerPort: 3030
          env:
            - name: PORT
              value: '3030'
            - name: NATS_SERVICE_CONNECTION
              value: 'nats-server:4222'
